import { RequiredDataFromCollectionSlug } from 'payload'

export const luxeCustomers: () => any[] = () => {
  return [
    {
      firstName: 'Amara',
      lastName: 'Kimani',
      fullName: 'Amara Kimani',
      email: 'amara.kimani@email.com',
      phone: '+254 712 345 678',
      dateOfBirth: '1990-03-15',
      gender: 'female',
      addresses: [
        {
          label: 'Home',
          firstName: 'Amara',
          lastName: 'Kimani',
          company: '',
          address1: '15 Lavington Gardens',
          address2: 'Apartment 3B',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00100',
          country: 'KE',
          isDefault: true,
        },
        {
          label: 'Work',
          firstName: 'Amara',
          lastName: 'Kimani',
          company: 'Kimani & Associates Law Firm',
          address1: '245 Kenyatta Avenue',
          address2: '12th Floor',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00200',
          country: 'KE',
          isDefault: false,
        },
      ],
      totalOrders: 12,
      totalSpent: 342000,
      lastOrderDate: '2024-08-28',
      averageOrderValue: 28500,
      loyaltyPoints: 1710,
      customerSince: '2022-01-15',
      preferredContactMethod: 'email',
      marketingOptIn: true,
      favoriteCategories: ['Dresses', 'Outerwear'],
      notes: 'Frequent buyer of luxury items. Prefers natural fabrics and sustainable brands.',
    },
    {
      firstName: 'Zara',
      lastName: 'Ochieng',
      fullName: 'Zara Ochieng',
      email: 'zara.ochieng@gmail.com',
      phone: '+254 723 456 789',
      dateOfBirth: '1988-07-22',
      gender: 'female',
      addresses: [
        {
          label: 'Home',
          firstName: 'Zara',
          lastName: 'Ochieng',
          company: '',
          address1: '89 Riverside Drive',
          address2: '',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00100',
          country: 'KE',
          isDefault: true,
        },
      ],
      totalOrders: 18,
      totalSpent: 486000,
      lastOrderDate: '2024-09-01',
      averageOrderValue: 27000,
      loyaltyPoints: 2430,
      customerSince: '2021-09-12',
      preferredContactMethod: 'phone',
      marketingOptIn: true,
      favoriteCategories: ['Tops', 'Dresses', 'Accessories'],
      notes: 'Influencer customer. Often purchases new arrivals for social media content.',
    },
    {
      firstName: 'Fatima',
      lastName: 'Hassan',
      fullName: 'Fatima Hassan',
      email: 'fatima.hassan@yahoo.com',
      phone: '+254 734 567 890',
      dateOfBirth: '1985-11-08',
      gender: 'female',
      addresses: [
        {
          label: 'Home',
          firstName: 'Fatima',
          lastName: 'Hassan',
          company: '',
          address1: '67 Muthaiga Road',
          address2: '',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00621',
          country: 'KE',
          isDefault: true,
        },
        {
          label: 'Office',
          firstName: 'Fatima',
          lastName: 'Hassan',
          company: 'Global Hope Foundation',
          address1: '123 UN Avenue',
          address2: 'Suite 45',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00100',
          country: 'KE',
          isDefault: false,
        },
      ],
      totalOrders: 8,
      totalSpent: 224000,
      lastOrderDate: '2024-08-15',
      averageOrderValue: 28000,
      loyaltyPoints: 1120,
      customerSince: '2022-05-20',
      preferredContactMethod: 'email',
      marketingOptIn: true,
      favoriteCategories: ['Outerwear', 'Knitwear'],
      notes: 'Values sustainable and ethically made fashion. Professional wardrobe focus.',
    },
    {
      firstName: 'Grace',
      lastName: 'Wanjiku',
      fullName: 'Grace Wanjiku',
      email: 'grace.wanjiku@corporate.co.ke',
      phone: '+254 745 678 901',
      dateOfBirth: '1992-12-03',
      gender: 'female',
      addresses: [
        {
          label: 'Home',
          firstName: 'Grace',
          lastName: 'Wanjiku',
          company: '',
          address1: '34 Kileleshwa Lane',
          address2: 'House 12',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00800',
          country: 'KE',
          isDefault: true,
        },
      ],
      totalOrders: 5,
      totalSpent: 135000,
      lastOrderDate: '2024-08-30',
      averageOrderValue: 27000,
      loyaltyPoints: 675,
      customerSince: '2023-03-10',
      preferredContactMethod: 'email',
      marketingOptIn: true,
      favoriteCategories: ['Basics', 'Outerwear'],
      notes: 'Building professional wardrobe. Prefers classic, versatile pieces.',
    },
    {
      firstName: 'Priya',
      lastName: 'Patel',
      fullName: 'Priya Patel',
      email: 'priya.patel@business.com',
      phone: '+254 756 789 012',
      dateOfBirth: '1987-04-18',
      gender: 'female',
      addresses: [
        {
          label: 'Home',
          firstName: 'Priya',
          lastName: 'Patel',
          company: '',
          address1: '78 Parklands Avenue',
          address2: '',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00400',
          country: 'KE',
          isDefault: true,
        },
        {
          label: 'Business',
          firstName: 'Priya',
          lastName: 'Patel',
          company: 'Patel Enterprises',
          address1: '156 Westlands Square',
          address2: '8th Floor',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00600',
          country: 'KE',
          isDefault: false,
        },
      ],
      totalOrders: 15,
      totalSpent: 420000,
      lastOrderDate: '2024-09-02',
      averageOrderValue: 28000,
      loyaltyPoints: 2100,
      customerSince: '2021-11-25',
      preferredContactMethod: 'phone',
      marketingOptIn: true,
      favoriteCategories: ['Designer', 'Accessories', 'Outerwear'],
      notes: 'Entrepreneur with taste for luxury. Often purchases statement pieces.',
    },
    {
      firstName: 'Aisha',
      lastName: 'Mwangi',
      fullName: 'Aisha Mwangi',
      email: 'aisha.mwangi@creative.co.ke',
      phone: '+254 767 890 123',
      dateOfBirth: '1991-09-14',
      gender: 'female',
      addresses: [
        {
          label: 'Home',
          firstName: 'Aisha',
          lastName: 'Mwangi',
          company: '',
          address1: '92 Spring Valley Road',
          address2: '',
          city: 'Nairobi',
          state: 'Nairobi',
          zipCode: '00100',
          country: 'KE',
          isDefault: true,
        },
      ],
      totalOrders: 10,
      totalSpent: 320000,
      lastOrderDate: '2024-08-25',
      averageOrderValue: 32000,
      loyaltyPoints: 1600,
      customerSince: '2022-07-08',
      preferredContactMethod: 'email',
      marketingOptIn: true,
      favoriteCategories: ['Avant-garde', 'Designer', 'Tops'],
      notes: 'Creative professional interested in artistic and unique fashion pieces.',
    },
  ]
}
